name: Build and Deploy FastAPI App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: venv
          key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --no-cache-dir fastapi uvicorn

      - name: Run tests
        run: |
          . venv/bin/activate
          # You can add your test command here, e.g., pytest if you have tests
          # pytest tests/  # Uncomment and modify if you have tests

      - name: Build Docker image
        run: |
          docker build -t fastapi-app .

      - name: Run on EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          USER

