name: Build and Deploy FastAPI App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --no-cache-dir fastapi uvicorn

      - name: Build Docker image
        run: |
          docker build -t fastapi-app .

      - name: Run on EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          USER: ${{ secrets.EC2_USER }}
          HOST: ${{ secrets.EC2_HOST }}
        run: |
          echo "${PRIVATE_KEY}" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST "
            docker stop fastapi-app || true && 
            docker rm fastapi-app || true && 
            docker run -d --name fastapi-app -p 80:80 fastapi-app
          "

